spring:
  application:
    name: stock-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local} # ???? local, ?? ? ????? ????

kis:
  token-expiration: 86400 # KIS Open API? access_token ???? 24??
